### ISSUE TITLE
Support HPKP (HTTP Public-Key-Pinning, RFC 7469)

### ISSUE THREAD

**Issue by FiloSottile** [StalkR/hsts#1]
Just to know if it's considered out of scope for the project.

**Comment by StalkR** [comment]
Yes I've been thinking about it, while I don't need it immediately I might do it at some point, just for the sake of completion.
Also since it's a different RFC (https://tools.ietf.org/html/rfc7469) I think it would be a different package.

Then a client wanting both could do:

```
client.Transport = hpkp.New(hsts.New(client.Transport))
```

The downside of two packages is that we'd need two separate sets for domains with sts/pkp, and go generate would work two times. It could have been more efficient with one. I don't see a good name for a single package uniting both standards/features though. Any ideas?

Keeping this issue around as a reminder to do it :)

**Comment by StalkR** [comment]
I started thinking about it. HPKP is more complicated than HSTS as we have to intervene in the certification validation so I don't think we'll be able to have a [RoundTripper](http://godoc.org/net/http#RoundTripper) wrapping design like for HSTS, but maybe we can work with an [*http.Transport](http://godoc.org/net/http#Transport):
- it has a nice `DialTLS` function that we can set, allowing us to do the TLS connection and certificate validation
- we need access to `TLSClientConfig` to keep user choice on CAs, etc.

**Comment by StalkR** [comment]
I guess it's no longer necessary now :( [Intent To Deprecate And Remove: Public Key Pinning](https://groups.google.com/a/chromium.org/forum/#!msg/blink-dev/he9tr7p3rZ8/eNMwKPmUBAAJ).
Maybe we should support Expect-CT instead.
